export const DELHI_HOSPITALS = [
  "AIIMS Delhi",
  "Safdarjung Hospital",
  "Sir Ganga Ram Hospital",
  "Ganga Ram Institute",
  "Max Super Speciality Saket",
  "Max Smart Saket",
  "Max Patparganj",
  "Max Shalimar Bagh",
  "Fortis Escorts Heart Institute, Okhla",
  "Fortis Hospital, Shalimar Bagh",
  "Fortis Hospital, Vasant Kunj",
  "Apollo Hospital, Sarita Vihar",
  "Indraprastha Apollo",
  "BLK-Max Super Speciality, Rajendra Place",
  "Sir Ganga Ram City Hospital, Rajinder Nagar",
  "Moolchand Hospital, Lajpat Nagar",
  "Holy Family Hospital, Okhla",
  "St. Stephen's Hospital, Tis Hazari",
  "Lok Nayak Hospital (LNJP)",
  "GTB Hospital, Dilshad Garden",
  "RML Hospital",
  "Lady Hardinge Medical College",
  "Hindu Rao Hospital",
  "Deen Dayal Upadhyay Hospital",
  "Rajiv Gandhi Cancer Institute, Rohini",
  "Sri Balaji Action Medical, Paschim Vihar",
  "Jaipur Golden Hospital, Rohini",
  "Saroj Super Speciality, Rohini",
  "Sant Parmanand Hospital, Civil Lines",
  "Batra Hospital, Tughlakabad",
  "Primus Super Speciality, Chanakyapuri",
  "Manipal Hospital, Dwarka",
  "Venkateshwar Hospital, Dwarka",
  "Aakash Healthcare, Dwarka",
  "Artemis Hospital, Gurgaon",
  "Medanta — The Medicity, Gurgaon",
  "Fortis Memorial Research Institute, Gurgaon",
  "Paras Hospital, Gurgaon",
  "Columbia Asia, Gurgaon",
  "Kailash Hospital, Noida",
  "Jaypee Hospital, Noida",
  "Fortis Hospital, Noida",
  "Yatharth Super Speciality, Noida",
];

export const DELHI_LOCALITIES = [
  "Saket",
  "Hauz Khas",
  "Greater Kailash I",
  "Greater Kailash II",
  "Defence Colony",
  "Lajpat Nagar",
  "Karol Bagh",
  "Connaught Place",
  "Paharganj",
  "Rajinder Nagar",
  "Patel Nagar",
  "Civil Lines",
  "Model Town",
  "Pitampura",
  "Rohini Sector 3",
  "Rohini Sector 7",
  "Rohini Sector 11",
  "Rohini Sector 18",
  "Shalimar Bagh",
  "Ashok Vihar",
  "Punjabi Bagh",
  "Paschim Vihar",
  "Janakpuri",
  "Vikaspuri",
  "Uttam Nagar",
  "Dwarka Sector 1",
  "Dwarka Sector 6",
  "Dwarka Sector 7",
  "Dwarka Sector 10",
  "Dwarka Sector 12",
  "Dwarka Sector 18",
  "Dwarka Mor",
  "Vasant Kunj",
  "Vasant Vihar",
  "Chanakyapuri",
  "Mayur Vihar Phase 1",
  "Mayur Vihar Phase 3",
  "Patparganj",
  "Preet Vihar",
  "Laxmi Nagar",
  "Shahdara",
  "Dilshad Garden",
  "Yamuna Vihar",
  "Okhla",
  "Sarita Vihar",
  "Kalkaji",
  "Govindpuri",
  "Tughlakabad",
  "Malviya Nagar",
  "South Extension",
  "Tis Hazari",
  "Gurgaon Sector 14",
  "Gurgaon Sector 29",
  "Gurgaon Sector 56",
  "Gurgaon Sector 57",
  "Sohna Road, Gurgaon",
  "Golf Course Road, Gurgaon",
  "MG Road, Gurgaon",
  "Noida Sector 18",
  "Noida Sector 50",
  "Noida Sector 62",
  "Noida Sector 76",
  "Noida Sector 137",
  "Greater Noida West",
  "Faridabad Sector 21",
  "Faridabad NIT",
  "Ghaziabad Indirapuram",
  "Ghaziabad Vaishali",
];