/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RequestRouteImport } from './routes/request'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DonorIndexRouteImport } from './routes/donor.index'
import { Route as RequestVerifyingRouteImport } from './routes/request.verifying'
import { Route as RequestProofRouteImport } from './routes/request.proof'
import { Route as RequestMatchingRouteImport } from './routes/request.matching'
import { Route as RequestHospitalRouteImport } from './routes/request.hospital'
import { Route as RequestConfirmedRouteImport } from './routes/request.confirmed'
import { Route as RequestCompletedRouteImport } from './routes/request.completed'
import { Route as RequestBloodRouteImport } from './routes/request.blood'
import { Route as DonorRequestRouteImport } from './routes/donor.request'
import { Route as DonorRegisterRouteImport } from './routes/donor.register'
import { Route as DonorDashboardRouteImport } from './routes/donor.dashboard'
import { Route as DonorCoordinateRouteImport } from './routes/donor.coordinate'
import { Route as DonorAvailabilityRouteImport } from './routes/donor.availability'

const RequestRoute = RequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorIndexRoute = DonorIndexRouteImport.update({
  id: '/donor/',
  path: '/donor/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestVerifyingRoute = RequestVerifyingRouteImport.update({
  id: '/verifying',
  path: '/verifying',
  getParentRoute: () => RequestRoute,
} as any)
const RequestProofRoute = RequestProofRouteImport.update({
  id: '/proof',
  path: '/proof',
  getParentRoute: () => RequestRoute,
} as any)
const RequestMatchingRoute = RequestMatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => RequestRoute,
} as any)
const RequestHospitalRoute = RequestHospitalRouteImport.update({
  id: '/hospital',
  path: '/hospital',
  getParentRoute: () => RequestRoute,
} as any)
const RequestConfirmedRoute = RequestConfirmedRouteImport.update({
  id: '/confirmed',
  path: '/confirmed',
  getParentRoute: () => RequestRoute,
} as any)
const RequestCompletedRoute = RequestCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => RequestRoute,
} as any)
const RequestBloodRoute = RequestBloodRouteImport.update({
  id: '/blood',
  path: '/blood',
  getParentRoute: () => RequestRoute,
} as any)
const DonorRequestRoute = DonorRequestRouteImport.update({
  id: '/donor/request',
  path: '/donor/request',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorRegisterRoute = DonorRegisterRouteImport.update({
  id: '/donor/register',
  path: '/donor/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorDashboardRoute = DonorDashboardRouteImport.update({
  id: '/donor/dashboard',
  path: '/donor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorCoordinateRoute = DonorCoordinateRouteImport.update({
  id: '/donor/coordinate',
  path: '/donor/coordinate',
  getParentRoute: () => rootRouteImport,
} as any)
const DonorAvailabilityRoute = DonorAvailabilityRouteImport.update({
  id: '/donor/availability',
  path: '/donor/availability',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/request': typeof RequestRouteWithChildren
  '/donor/availability': typeof DonorAvailabilityRoute
  '/donor/coordinate': typeof DonorCoordinateRoute
  '/donor/dashboard': typeof DonorDashboardRoute
  '/donor/register': typeof DonorRegisterRoute
  '/donor/request': typeof DonorRequestRoute
  '/request/blood': typeof RequestBloodRoute
  '/request/completed': typeof RequestCompletedRoute
  '/request/confirmed': typeof RequestConfirmedRoute
  '/request/hospital': typeof RequestHospitalRoute
  '/request/matching': typeof RequestMatchingRoute
  '/request/proof': typeof RequestProofRoute
  '/request/verifying': typeof RequestVerifyingRoute
  '/donor/': typeof DonorIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/request': typeof RequestRouteWithChildren
  '/donor/availability': typeof DonorAvailabilityRoute
  '/donor/coordinate': typeof DonorCoordinateRoute
  '/donor/dashboard': typeof DonorDashboardRoute
  '/donor/register': typeof DonorRegisterRoute
  '/donor/request': typeof DonorRequestRoute
  '/request/blood': typeof RequestBloodRoute
  '/request/completed': typeof RequestCompletedRoute
  '/request/confirmed': typeof RequestConfirmedRoute
  '/request/hospital': typeof RequestHospitalRoute
  '/request/matching': typeof RequestMatchingRoute
  '/request/proof': typeof RequestProofRoute
  '/request/verifying': typeof RequestVerifyingRoute
  '/donor': typeof DonorIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/request': typeof RequestRouteWithChildren
  '/donor/availability': typeof DonorAvailabilityRoute
  '/donor/coordinate': typeof DonorCoordinateRoute
  '/donor/dashboard': typeof DonorDashboardRoute
  '/donor/register': typeof DonorRegisterRoute
  '/donor/request': typeof DonorRequestRoute
  '/request/blood': typeof RequestBloodRoute
  '/request/completed': typeof RequestCompletedRoute
  '/request/confirmed': typeof RequestConfirmedRoute
  '/request/hospital': typeof RequestHospitalRoute
  '/request/matching': typeof RequestMatchingRoute
  '/request/proof': typeof RequestProofRoute
  '/request/verifying': typeof RequestVerifyingRoute
  '/donor/': typeof DonorIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/request'
    | '/donor/availability'
    | '/donor/coordinate'
    | '/donor/dashboard'
    | '/donor/register'
    | '/donor/request'
    | '/request/blood'
    | '/request/completed'
    | '/request/confirmed'
    | '/request/hospital'
    | '/request/matching'
    | '/request/proof'
    | '/request/verifying'
    | '/donor/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/request'
    | '/donor/availability'
    | '/donor/coordinate'
    | '/donor/dashboard'
    | '/donor/register'
    | '/donor/request'
    | '/request/blood'
    | '/request/completed'
    | '/request/confirmed'
    | '/request/hospital'
    | '/request/matching'
    | '/request/proof'
    | '/request/verifying'
    | '/donor'
  id:
    | '__root__'
    | '/'
    | '/request'
    | '/donor/availability'
    | '/donor/coordinate'
    | '/donor/dashboard'
    | '/donor/register'
    | '/donor/request'
    | '/request/blood'
    | '/request/completed'
    | '/request/confirmed'
    | '/request/hospital'
    | '/request/matching'
    | '/request/proof'
    | '/request/verifying'
    | '/donor/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RequestRoute: typeof RequestRouteWithChildren
  DonorAvailabilityRoute: typeof DonorAvailabilityRoute
  DonorCoordinateRoute: typeof DonorCoordinateRoute
  DonorDashboardRoute: typeof DonorDashboardRoute
  DonorRegisterRoute: typeof DonorRegisterRoute
  DonorRequestRoute: typeof DonorRequestRoute
  DonorIndexRoute: typeof DonorIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/request': {
      id: '/request'
      path: '/request'
      fullPath: '/request'
      preLoaderRoute: typeof RequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor/': {
      id: '/donor/'
      path: '/donor'
      fullPath: '/donor/'
      preLoaderRoute: typeof DonorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request/verifying': {
      id: '/request/verifying'
      path: '/verifying'
      fullPath: '/request/verifying'
      preLoaderRoute: typeof RequestVerifyingRouteImport
      parentRoute: typeof RequestRoute
    }
    '/request/proof': {
      id: '/request/proof'
      path: '/proof'
      fullPath: '/request/proof'
      preLoaderRoute: typeof RequestProofRouteImport
      parentRoute: typeof RequestRoute
    }
    '/request/matching': {
      id: '/request/matching'
      path: '/matching'
      fullPath: '/request/matching'
      preLoaderRoute: typeof RequestMatchingRouteImport
      parentRoute: typeof RequestRoute
    }
    '/request/hospital': {
      id: '/request/hospital'
      path: '/hospital'
      fullPath: '/request/hospital'
      preLoaderRoute: typeof RequestHospitalRouteImport
      parentRoute: typeof RequestRoute
    }
    '/request/confirmed': {
      id: '/request/confirmed'
      path: '/confirmed'
      fullPath: '/request/confirmed'
      preLoaderRoute: typeof RequestConfirmedRouteImport
      parentRoute: typeof RequestRoute
    }
    '/request/completed': {
      id: '/request/completed'
      path: '/completed'
      fullPath: '/request/completed'
      preLoaderRoute: typeof RequestCompletedRouteImport
      parentRoute: typeof RequestRoute
    }
    '/request/blood': {
      id: '/request/blood'
      path: '/blood'
      fullPath: '/request/blood'
      preLoaderRoute: typeof RequestBloodRouteImport
      parentRoute: typeof RequestRoute
    }
    '/donor/request': {
      id: '/donor/request'
      path: '/donor/request'
      fullPath: '/donor/request'
      preLoaderRoute: typeof DonorRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor/register': {
      id: '/donor/register'
      path: '/donor/register'
      fullPath: '/donor/register'
      preLoaderRoute: typeof DonorRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor/dashboard': {
      id: '/donor/dashboard'
      path: '/donor/dashboard'
      fullPath: '/donor/dashboard'
      preLoaderRoute: typeof DonorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor/coordinate': {
      id: '/donor/coordinate'
      path: '/donor/coordinate'
      fullPath: '/donor/coordinate'
      preLoaderRoute: typeof DonorCoordinateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donor/availability': {
      id: '/donor/availability'
      path: '/donor/availability'
      fullPath: '/donor/availability'
      preLoaderRoute: typeof DonorAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RequestRouteChildren {
  RequestBloodRoute: typeof RequestBloodRoute
  RequestCompletedRoute: typeof RequestCompletedRoute
  RequestConfirmedRoute: typeof RequestConfirmedRoute
  RequestHospitalRoute: typeof RequestHospitalRoute
  RequestMatchingRoute: typeof RequestMatchingRoute
  RequestProofRoute: typeof RequestProofRoute
  RequestVerifyingRoute: typeof RequestVerifyingRoute
}

const RequestRouteChildren: RequestRouteChildren = {
  RequestBloodRoute: RequestBloodRoute,
  RequestCompletedRoute: RequestCompletedRoute,
  RequestConfirmedRoute: RequestConfirmedRoute,
  RequestHospitalRoute: RequestHospitalRoute,
  RequestMatchingRoute: RequestMatchingRoute,
  RequestProofRoute: RequestProofRoute,
  RequestVerifyingRoute: RequestVerifyingRoute,
}

const RequestRouteWithChildren =
  RequestRoute._addFileChildren(RequestRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RequestRoute: RequestRouteWithChildren,
  DonorAvailabilityRoute: DonorAvailabilityRoute,
  DonorCoordinateRoute: DonorCoordinateRoute,
  DonorDashboardRoute: DonorDashboardRoute,
  DonorRegisterRoute: DonorRegisterRoute,
  DonorRequestRoute: DonorRequestRoute,
  DonorIndexRoute: DonorIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
